### ISSUE TITLE
With 1.11 stable snap, I got this error: /usr/share/libdrm/amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by antonyshen** [Nightmayr-snaps/ppsspp-snap#1]
$ ppsspp-emu.ppsspp-sdl 
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
/usr/share/libdrm/amdgpu.ids: No such file or directory
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
/usr/share/libdrm/amdgpu.ids: No such file or directory
X Error:  BadAlloc
  Request Major code 148 ()
  Request Minor code 2
  Error Serial #100
  Current Serial #101

It appears the correct way to solve this issue is documented here:

https://forum.snapcraft.io/t/amd-oss-graphics-drivers-missing-access-to-amdgpu-ids-file/12067/14

**Comment by Nightmayr** [comment]
I've pushed the fix to the edge channel. I don't seem to get the error anymore with my AMD GPU. Let me know if it's solved the problem for you.

**Comment by antonyshen** [comment]
Hi Nightmayr

Just tried, seems still the same.

~$ sudo snap install ppsspp-emu --edge
ppsspp-emu (edge) 1.11 from Umayr Saghir (nightmayr) installed
~$ ppsspp-emu.ppsspp-sdl 
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
/usr/share/libdrm/amdgpu.ids: No such file or directory
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
/usr/share/libdrm/amdgpu.ids: No such file or directory
X Error:  BadAlloc
  Request Major code 148 ()
  Request Minor code 2
  Error Serial #100
  Current Serial #101
~$ ls -al /usr/share/libdrm/amdgpu.ids
-rw-r--r-- 1 root root 10082 Jan 11 10:15 /usr/share/libdrm/amdgpu.ids

**Comment by Nightmayr** [comment]
Sorry about that didn't realise the build for edge failed. The fix should now be in the edge channel revision 5.

**Comment by antonyshen** [comment]
Hi Nightmayr

Just update the snap, it behaves differently, but still failed, can you check again? Thanks.

~$ snap list 
Name               Version          Rev    Tracking       Publisher   Notes
core18             20210128         1988   latest/stable  canonical✓  base
core20             20201210         904    latest/stable  canonical✓  base
gtk-common-themes  0.1-50-gf7627e4  1514   latest/stable  canonical✓  -
lxd                4.11             19566  latest/stable  canonical✓  -
ppsspp-emu         1.11.2           5      latest/edge    nightmayr   -
snapd              2.48.2.1         11036  latest/stable  canonical✓  snapd
~$ ppsspp-emu.ppsspp-sdl 
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #104
  Current Serial #105

**Comment by Nightmayr** [comment]
Seems to be a problem with Xorg from what I can tell? Can I get the following info:

- Which distro you're using
- hardware specs
- Output of `snap version`

Based on that info I'll see if there's a way for me to recreate the error you're seeing, as I'm currently unable to see this error on an Ubuntu 20.10 vm with an AMD RX580

**Comment by antonyshen** [comment]
Hi Nightmayr,

My PC is Lenovo ThinkCentre M75q Gen 2, equipped with a Ryzen 7 Pro 4750GE APU.

I am running Ubuntu 21.04. The version of snap is:

~$ snap --version
snap    2.49+21.04build1
snapd   2.49+21.04build1
series  16
ubuntu  21.04
kernel  5.10.0-14-generic

**Comment by antonyshen** [comment]
Hi Nightmayr,

Today I tried Ubuntu 20.10 on the same PC, still got the same error. Below are messages copy from terminal:

~$ snap refresh --edge ppsspp-emu 
ppsspp-emu (edge) 1.11.3 from Umayr Saghir (nightmayr) refreshed
~$ ppsspp-emu.ppsspp-sdl                       
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 18
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #104
  Current Serial #105

~$ snap --version
snap    2.48.3+20.10
snapd   2.48.3+20.10
series  16
ubuntu  20.10
kernel  5.10.19-xanmod1


~$ snap list
Name               Version                     Rev    Tracking       Publisher   Notes
0ad                0.0.24b-alpha               197    latest/stable  play0ad✓    -
core               16-2.48.2.1                 10823  latest/stable  canonical✓  core
core18             20201210                    1944   latest/stable  canonical✓  base
core20             20201210                    904    latest/stable  canonical✓  base
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  145    latest/stable  canonical✓  -
gtk-common-themes  0.1-50-gf7627e4             1514   latest/stable  canonical✓  -
lxd                4.9                         18772  latest/stable  canonical✓  -
ppsspp-emu         1.11.3                      6      latest/edge    nightmayr   -
snapd              2.48.2.1                    11036  latest/stable  canonical✓  snapd

**Comment by Nightmayr** [comment]
I was able to try setting up an ubuntu 21.04 vm with `snap --version` giving me the same output as your 21.04 machine, however the snap worked perfectly fine for me so I wasn't able to reproduce this bug. I notice you installed 0ad, does that snap work as expected? Do you experience similar errors with other snaps?

**Comment by antonyshen** [comment]
Hi Nightmayr,

So far I tried two gaming related snaps, ppsspp and 0ad, 0ad has similar issue too, however I have no issue with wine+dxvk games.

This is what 0ad would show up:
~$ 0ad
TIMER| InitVfs: 15.8123 ms
Writing the mainlog at /home/antony/snap/0ad/197/.config/0ad/logs/mainlog.html
TIMER| CONFIG_Init: 1.78861 ms
Sound: AlcInit success, using OpenAL Soft
TIMER| shutdown ConfigDB: 0.32 us
TIMER| resource modules: 1.07317 ms
TIMER TOTALS (9 clients)
-----------------------------------------------------
  tc_pool_alloc: 0 c (0x)
  tc_png_decode: 0 c (0x)
  tc_dds_transform: 0 c (0x)
  tc_transform: 0 c (0x)
  tc_plain_transform: 0 c (0x)
  tc_ShaderGLSLLink: 0 c (0x)
  tc_ShaderGLSLCompile: 0 c (0x)
  tc_ShaderValidation: 0 c (0x)
  xml_validation: 0 c (0x)
-----------------------------------------------------
TIMER| shutdown misc: 113.304 us
TIMER| InitVfs: 91.1219 ms
Writing the mainlog at /home/antony/snap/0ad/197/.config/0ad/logs/mainlog.html
TIMER| CONFIG_Init: 1.25077 ms
Sound: AlcInit success, using OpenAL Soft
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #104
  Current Serial #105
UserReport.cpp(516): Assertion failed: "!m_Worker"
Assertion failed: "!m_Worker"
Location: UserReport.cpp:516 (~CUserReporter)

Call stack:

(0x563da1fa7aee) /snap/0ad/197/binaries/system/pyrogenesis(+0x5a7aee) [0x563da1fa7aee]
(0x563da1f4d401) /snap/0ad/197/binaries/system/pyrogenesis(+0x54d401) [0x563da1f4d401]
(0x563da1f4f48e) /snap/0ad/197/binaries/system/pyrogenesis(+0x54f48e) [0x563da1f4f48e]
(0x563da1cd36d3) /snap/0ad/197/binaries/system/pyrogenesis(+0x2d36d3) [0x563da1cd36d3]
(0x7fb75c477161) /lib/x86_64-linux-gnu/libc.so.6(+0x43161) [0x7fb75c477161]
(0x7fb75c47725a) /lib/x86_64-linux-gnu/libc.so.6(+0x4325a) [0x7fb75c47725a]
(0x7fb75e619788) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x40788) [0x7fb75e619788]
(0x7fb75e6198ba) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(_XError+0x11a) [0x7fb75e6198ba]
(0x7fb75e6167eb) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x3d7eb) [0x7fb75e6167eb]
(0x7fb75e616895) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(+0x3d895) [0x7fb75e616895]
(0x7fb75e6171c5) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(_XEventsQueued+0x55) [0x7fb75e6171c5]
(0x7fb75e619f85) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libX11.so.6(_XGetRequest+0x55) [0x7fb75e619f85]
(0x7fb71f5bbbb2) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0(+0x34bb2) [0x7fb71f5bbbb2]
(0x7fb7610e07b3) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0xcb7b3) [0x7fb7610e07b3]
(0x7fb7610b3746) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0x9e746) [0x7fb7610b3746]
(0x7fb7610b58e4) /snap/0ad/197/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0(+0xa08e4) [0x7fb7610b58e4]

errno = 0 (?)
OS error = ?


AL lib: (EE) alc_cleanup: 1 device not closed
(C)ontinue, (S)uppress, (B)reak, Launch (D)ebugger, or (E)xit?
E
Redirecting call to abort() to mozalloc_abort


Below is what I got from lutris:
[System]
OS:              Ubuntu 21.04 hirsute
Arch:            x86_64
Kernel:          5.10.0-14-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 PRO 4750GE with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             30.8 GB
Swap:            79.4 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD RENOIR (DRM 3.40.0, 5.10.0-14-generic, LLVM 11.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 20.3.4
OpenGL Core:     4.6 (Core Profile) Mesa 20.3.4
OpenGL ES:       OpenGL ES 3.2 Mesa 20.3.4
Vulkan:          Supported

**Comment by Nightmayr** [comment]
Thanks for letting me know 0ad has the same problem, I suspect this is something specific with your setup. Unfortunately I'm not too sure how to proceed with this. I would raise this over at https://forum.snapcraft.io/c/snap/14 by creating a forum post with the details you've posted here, bringing attention to the error common to both `ppsspp-emu` and `0ad`: 
```
X Error: BadAlloc
Request Major code 149 ()
Request Minor code 2
Error Serial #104
Current Serial #105
```
The community there may have some ideas as to what's causing this error

**Comment by antonyshen** [comment]
Hi Nightmayr,

OK. When you raise the discussion, please share the link. I could provided more info regarding to my current installation if needed. Thanks.

**Comment by Nightmayr** [comment]
Hi sorry for the delayed response, I can try and get round to creating that post at some point, unfortunately I've been quite busy in my personal life and my day job. If you want to speed this up feel free to create the forum post yourself, and I can provide any additional information if required, Thanks
